### ISSUE TITLE
Нет реквестов по ДЗ

### ISSUE THREAD

**Issue by MasalitinMaksim** [FrozenCrash/come2us#15]
Ребята, когда от вас ждать сдачи ДЗ 11-12?
До сих пор от вас не пришло ни одного реквеста. Начинаю за вас волноваться)

**Comment by rostyslav-m** [comment]
Максим, 
посмотрите, пожалуйста,
ветка dev обновлена в соответствии с Вашими замечаниями.

Нужно ли делать новый реквест или Вы примете уже открытый?
